---
layout: post
title: Dad Weeknotes, volume 3
tags:
  - dadding
  - weeknotes
---

This is my third week of dadding.  You may also want to see [[/2018/01/13/dad-weeknotes-1.html][volume 1]]
and [[/2018/01/20/dad-weeknotes-2.html][volume 2]].

** Nursery

Thursday was Luke's first day at nursery.  Sonia and I went with him
and stayed in the class for the morning, then took him home.  Luke is
in the baby room, which is ages from 6 months to 2 years.  The day has
a structure to it: at 9.30am is "circle time" where they sit in a
circle and have songs.  They then go and wash their hands (the littler
ones are helped with this) and sit at tables to have milk and fruit.
Then there is some outdoor free play time.

Luke did really well – he seemed happier eating at nursery than he had
been at breakfast at home!  However the nursery schedule doesn't align
well with his existing schedule and before long he was very tired.  We
put him in the pram to sleep and took him home again, 45 minutes
earlier than planned.

On Friday, I took him in again (Sonia had work commitments so couldn't
join us), but this time I left him there.  He seemed to sit down for
circle time well.  I went to a nearby café in case there were any
problems and they tried to call.  We had arranged for me to pick him
up again at 12 noon.

As soon as I left him, I felt really odd.  I didn't want to walk too
far away in case I was needed, but I also knew I wasn't likely to
actually be called on.  I still had the feeling of needing to look
after Luke and having to think about him and his needs, but I had
literally nothing to do.  As a result, I kept thinking through whether
I had done everything right this morning.  Did I bring everything he
needed?  I had brought his shoes, but I didn't tell the nursery staff
where I'd put them.  Would they find them?  Would he end up playing
outside in his stocking feet?  Was that a problem?

After half an hour nursing a coffee in the café and trying to read my
book, I admitted there was nothing to do so I went back home.  Sonia
was still busy with work calls.  So I sat on the sofa and tried to
distract myself from the ongoing emotional wrench.

Sonia finished her call about 11am, and came through to give me a hug.
Having her there was a huge relief.

She wanted to get some exercise, so we arranged that she would go and
pick Luke up while I prepared lunch.  On her way to the nursery, the
staff called her!  It turns out Luke had had a tough morning and they
wanted to let her know.  He had done well at circle time but he was
confused by the transitions between different activities.  He got
tired but managed to sleep in his pram a little.  But at lunchtime he
was too upset to be able to eat anything.

Luke is only booked in to nursery two days a week at the moment, but
it's possible to take him in on other days if we stay with him.  We
will probably do this next week to help him get more used to the
environment and the timetable of activities.

** Luke's affect

Luke has started to get angry and upset quite quickly if he can't do
things.  For example, the oven door handle is at a great height for
him to reach and pull himself up, but we'd quite like him not to play
with the oven door.  Previously, I could just pick him up and move him
somewhere else, and he'd be happy; this week, however, he has found
things like this much more upsetting.

He has also been variable at mealtimes: sometimes he will eat as
normal, sometimes he won't eat food he would usually wolf down.  We
were particularly surprised one morning when he wouldn't swallow his
raspberries – normally a favourite.

We have developed a number of hypotheses about what could be causing
this: is it just a new stage of development?  Is he slightly ill, or
teething?  (He has also been sleeping more than usual, which is
consistent with this.)  Was the nursery visit a traumatic experience
for him, which is still affecting him?

Right now, we think it's most likely that he's slightly ill, but we
will keep an eye on it.  We can always take him to the weekly health
visitor clinic on Tuesday if we're still concerned.

** Washing-up gloves

Being a man, and an above-average-sized man at that, normal washing-up
gloves don't fit me.  When I put my hand on the Marigold width guide,
it covers the whole thing up, suggesting that I wouldn't even squeeze
into the largest size available.

Until now, I had just accepted this and washed up bare-handed.  That's
fine when you're doing it once a day, but when you're washing up 3 or
4 times a day, it really affects your skin.  I found the knuckles on
my right hand getting drier and drier, and cracking painfully, and the
cracks not healing.  I realised this was not a sustainable situation
so I set out to find some gloves which do fit me.

It turns out that while Marigold don't do an XL size, some other
brands do.  And it also turns out there's such a thing as moisturizing
gloves!

So, for the moment I'm using [[http://www.lakeland.co.uk/p21178/Deluxe-Moisturising-Gloves][Lakeland Deluxe Moisturizing Gloves]] in
Large size. Large is tolerable for me, but I'm going to try XL as well
to see if it's a better fit.  The cracking on my knuckles has healed
up well now, and washing up is much less painful.

** Visit from Grandma

My mum had a flying visit this week.  She lives in Glasgow but often
has meetings in London, and she usually stays with us when she does.
She came on Tuesday evening, and left Wednesday morning at 11am.  It
was great to see her.

We weren't sure if Luke would remember her.  He last saw her a month
previously, which is a tenth of his whole life so far.  But when she
came in the front door, Luke immediately had big smiles for his
grandma.  They had a lot of fun together, reading stories and playing
with his walking trolley.

I took advantage of this to do something I had been trying to get done
for days: wash my hair and have a shave!

Having a child has definitely changed my relationship with my mum.
It's a joy to see her be so proud of Luke.  She really enjoys her role
as grandma, and Luke brings out the best in her (as he does with all
his grandparents).  I also seek her support much more than I used to,
and she has a lot of support to offer.

** Argh I don't know how to end this

I'm still working out the format.  Will this do?
