---
layout: post
title: Dad Weeknotes, volume 7
tags:
  - dadding
  - weeknotes
---

[[/2018/02/17/dad-weeknotes-6.html][Previously, on Phil's dad weeknotes..]]

** Planning for return to work

It feels like I only just started these notes but it will soon be time for
them to end (as we know them at least): I only have a week and a half before
returning to work.  I've really enjoyed and valued the time I've had caring
for Luke and it's going to be a hard adjustment to go back to full-time work
and not see nearly so much of him.

Sonia and I have had some conversations about the new routine.  One
practical thing we have had to address is that the nursery doesn't have
enough space during March -- Luke will be in for 3 days a week but we wanted
4 -- so we need to work out how we will care for Luke in that month.
Thankfully, I have plenty of annual leave left so I can take some leave to
care for Luke on some of those extra days.

We have tried to replan Luke's morning routine.  The current routine we're
in means that Sonia often doesn't start work til around 9.30, because she
has to look after Luke while I have my shower, and she has her shower
afterwards.  This has been okay for the moment but isn't really
sustainable.

We have also had some difficult conversations about hazards that
Sonia anticipates.  One is that, with Sonia working from home, it may well fall
to her by default to ensure Luke's dinner is ready for him when he gets home
from nursery.

It's important for us to keep talking about this.  We won't come up with the
perfect plan on day one of me going back to work, but we can reflect on what
works and what doesn't and iterate our routine so that it works for all
three of us, without placing unfair burden on anyone.

** Language development

Luke has definitely shown some signs of developing language.  He has already
been babbling for some time, but recently he has started to seem more
deliberate in his use of sounds.  When I go and get him up in the morning,
he says "Dad! Dad Dad Dad Dad Daaaad" with a variety of tones and
inflections.  This is exciting, but my feelings of pride are tempered
somewhat because this week he has also said "Dad" when looking at: his mum,
his granddad, and a piece of cucumber.

One thing that is far more clear is that he is starting to recognise things
that we say and respond appropriately.  During mealtimes, Luke often focuses
on his food and forgets to drink his water.  When I say "have a drink,
Luke", though, he knows to pick up his cup and (hopefully) have a drink from
it, or (all too often) see what sound it makes when he bangs it on the
table, or turn it upside down and dribble the water out.  We have some books
which have a common item on each page (such as "That's Not My Snowman" which
has a mouse on each page, or "This Little Dinosaur" which has a ladybird, or
"Wow! Said The Owl" which has an owl), and Luke has learned to go hunting
for it when we say "Where's the mouse, Luke?" or "Where's the owl, Luke?".

** Milk ladder

As mentioned last week, we've started on the milk ladder.  He's done very
well with the biscuits baked by grandma, and so we moved on to muffins.  I
baked some carrot and dairy-free cheese muffins (made with a specific amount
of milk) and he has been having half a muffin and some biscuits with his
breakfast over the past few days.  So far, we haven't seen any definite
reaction, so this is really good news.

Luke continues to drink some coconut milk, though not as much as we would
like.  He had about 40ml of coconut milk this morning, which isn't too bad,
and is far more than the oat milk we were trying before.

** Supporting mum's work trip

Luke's mum Sonia returned to work at the start of January, and this week she
needed to be in St Andrews in Scotland for some work meetings.  Since Luke
is still breastfeeding, this is somewhat complicated.  We considered a few
options for how I might look after Luke in London while Sonia went to St
Andrews: I could substitute with formula while she was away, or Sonia could
express breast milk and store it up in the freezer.  However, as mentioned
in previous weeks, we haven't found a dairy-free (or extensively-hydrolysed)
formula that Luke will reliably drink.  We have also had significant
spoilage problems with freezing breast milk -- often half of the batches I
defrosted would have gone foul in some way.

As a result, by far the easiest option was for us all to travel to St
Andrews.  I'm still on Shared Parental Leave, after all, so I have nothing
tying me to London, and if we all go then Sonia can continue to breastfeed
Luke in the morning and evening and do her work stuff during the day.  We
can also stay with Sonia's parents who can provide additional support with
cooking, cleaning, and cuddles.

In other house-husbanding news, I very much enjoyed sewing some buttons on
to mine and Sonia's coats while watching Star Trek Discovery.

** Nursery

Luke missed his usual full-time days at nursery on Thursday and Friday, but
I was able to take him in to nursery for an hour on Monday and Tuesday.
There were 3 parents with babies in on Monday, which was slightly more than
the nursery had chairs for, so on Tuesday they asked us to come in at
staggered times.  This meant I brought Luke in in the afternoon instead,
which is something I've never done before.  Normally I take him in for an
hour or two between 9 and 11, but on Tuesday it was 2.30 to 3.30.

It was almost like Luke was a different baby!  When I take him in around 9,
he usually stays very close to me, and even if he crawls off to explore or
to play with a toy he's spotted, he frequently checks to see I'm still there
and still looking at him.  But on Tuesday, he was off, crawling quite far
away, to places which were almost out of site, not looking back nearly as
frequently.

It's hard to know exactly what your own baby is like at nursery when you're
not there, when all you have to go on is how they are when you drop them off
or pick them up.  I worry about Luke, but this made me worry a little bit
less.

With the work trip to St Andrews, it means Luke is going to have quite a
long break from nursery.  We're bracing for re-entry when we take Luke back.
It's probably going to take him some getting used to again.

** Quaker meeting

On Thursday I took Luke to his first Quaker meeting, in
[[http://www.quakerscotland.org/st-andrews][St
Andrews].  It was a small meeting, with just 9 people (including Luke) and a
dog.  Luke behaved himself pretty well.  I kept him strapped in his
pushchair, and he sat and chatted away to himself.  It wasn't the most
silent Quaker meeting I've been to, but I think people appreciated Luke's
presence anyway.  The dog (called Gunnar) also made his presence known,
occasionally walking around and making friends with those present.

Two of the attenders were students who were attending a meeting for the
first time.  The welcomer, who had given them a brief introduction to the
Quakers and a copy of [[http://qfp.quaker.org.uk/chapter/1/][Advices &
Queries]] beforehand, explained to the students afterward that she hadn't been to
a meeting quite like that before either!  8 adults, a baby and a dog does
make for a unique Quaker meeting experience.

