---
layout: post
title: Dad Weeknotes, volume 2
tags:
  - dadding
  - weeknotes
---

It's volume two of my much-celebrated dad weeknotes!

** Baby health

We're trying out [[https://www.smababy.co.uk/formula-milk/wysoy-infant-formula/][SMA Wysoy]], a soya-based infant formula.  As
previously mentioned, Luke has a non-IgE cow's milk protein allergy.
He is still breastfed, but there are times when breastmilk is
impractical or inconvenient (for example, Sonia has work trips roughly
once a month).  We have previously tried expressing and storing milk,
with some success but with issues I won't go into here.  We have also
tried extensively hydrolysed formulas – these use cow's milk but
hydrolyse the protein until it is no longer a trigger for the allergy.
However they taste disgusting and Luke could not get used to the
flavour.

As a result, we're trying the soya formula, so that Luke has something
for nursery and for when Sonia is away.

** Nursery

We had our preparatory home visit from our nursery key worker.  She
will be assigned to Luke, so when he starts nursery this coming
Thursday she will be there to welcome him.  Of course, Luke slept
through the whole home visit so they didn't actually get to meet each
other.

There was a lot of paperwork.  It was a pretty badly-designed form: it
asked for lots of information multiple times but in different ways, it
had inconsistent style (sometimes you sign then print your name,
sometimes you print then sign).

** Mental health

This has been a tough week for my mental health.  I have suffered from
depression in the past, and this week I felt some of those same
feelings returning.  Being primary carer for a baby, it's easy to get
overwhelmed.  Also, being naturally perfectionist, it's easy to be
hard on myself when there isn't time or energy to achieve the high
standards I set myself.

What was good was that my wife and I both recognised it instantly and
were able to talk about it straight away.  We talked about feelings,
but just as importantly we talked about /beliefs/ – often, bad
feelings arise due to incorrect beliefs.  Often I don't even realise I
have these beliefs but they are there, causing trouble.  Especially
beliefs that start with the works "I should": "I should always know
why Luke is crying", "I should always have home-cooked food prepared
for Luke rather than rely on a ready-made pouch", "I should be better
at this than I am".  When my behaviour doesn't live up to my beliefs,
it's easy to examine my behaviour, but it's just as important to
examine the beliefs.

** Food and cooking

I've been trying to develop a repertoire of meals that meet certain
criteria:

  - low effort-per-portion
  - storable and reheatable
  - good for Luke to feed himself
  - good balance of nutrients
  - dairy-free
  - flexible scheduling (ie, can you easily pause the cooking halfway
    through, or do some steps the night before?)

In the past, we have done big batches of soup, which could easily tick
all of these criteria.  However, Luke is getting more and more keen to
feed himself rather than be spoonfed.  This week I tried to find some
recipes which Luke could eat with his hands.  Here are some of the
things I tried:

*** Multicolour casserole

This was from a toddler recipe book.  It's basically garden peas,
sweetcorn and diced red pepper, simmered in vegetable stock for a few
minutes.  It's good finger food in that it gets Luke to practice
picking up small objects.

However, as a whole meal, it turned out to be too much sustained
effort for Luke, and he got very upset before he had eaten half his
portion.  In following meals, we gave him small amounts of the
casserole alongside a less demanding main course.  By the time we got
to the bottom of the batch, we were blending it with a hand blender to
make it easier for Luke to eat.

*** Dairy-free fish pie

We bodged together this recipe from bits and pieces on the internet.
In short:

  - put the potatoes on to boil
  - fry some onions and leeks
  - add [[https://www.kokodairyfree.com/][koko coconut milk]] to the pan, and poach the fish in it
  - carefully remove the fish from the pan, and strain the poaching
    liquid into a jug
  - make parsley sauce from a roux, the poaching liquid, and lots of
    chopped parsley
  - mash the potatoes and mix in some margarine
  - layer the fish, parsley sauce and mash in a rectangular dish
  - oven for 30 minutes

This felt like a huge amount of effort, even if we got 7 portions out
of it.  On the plus side, it's quite easy to do every step before the
oven, and put it in the fridge to store until it's needed.  That means
you can cook in the evening, when you have time, for lunch the next
day, when you don't.

Luke loved the fish pie.  It's got big enough chunks of fish that he
can eat them on their own with his hands, and the mash and parsley
sauce combine to make clumpy balls which he can also feed himself.

*** Roast chicken

In principle a roast isn't a lot of effort: take chicken, put in oven,
wait.  Makes several portions.

It's the stuff around it that makes a roast take a lot of effort.  We
had it with roast potatoes, red cabbage with apple, and gravy. I
probably made a mistake doing a red-cabbage-and-apple side dish – that
could have just been simply broccoli or peas.

Luke enjoyed the chicken but, with only four teeth still, it's still a
bit much for him to chew up strips of the stuff.  He absolutely loves
roast potatoes though, we can't feed him enough of them.  Although I
thought I had cooked the red cabbage until soft, it was still a bit
tricky for Luke to chew properly.

I simmered the carcass for stock afterward, and hopefully we'll get a
good batch of chicken soup out of it.

** Summary of the week

Sometimes it feels like taking over primary responsibility as a parent
is like trying to jump on to a moving vehicle: Sonia can support me
and explain to me things as they are, but Luke is developing and
changing constantly, so what worked last week may not work any more.
I'm having to play catch-up at the same time as anticipating Luke's
future development.
