---
layout: post
title: Dadding, back at work
tags:
  - dadding
  - weeknotes
---

[[/2018/02/25/dad-weeknotes-7.html][Previously, on Phil's dad weeknotes..]]

I returned to work from my 14 weeks Shared Parental Leave on 6th
March.  I stopped doing dad weeknotes after I returned to work, but I
thought it was worth another update, because there are things worth
writing about in Luke's development and in my return to work.

** The new routine

To be honest, it's been a bit of a bumpy reentry, in terms of working
out a new routine that works for my work, my wife Sonia's work, and
Luke's childcare.  On top of that, nursery has been the expected
melting pot of pathogens, and we all got a pretty horrible viral
infection (I was affected for about 4 weeks, and had 2-3 weeks total
time off work as a result).  But we're just about getting settled into
a routine that works.

Luke is in nursery 4 days a week (every day except Wednesday), 9am to
5pm.  Every morning, we need to get him out of bed, change his nappy,
prepare his breakfast, give him breakfast, get him dressed, and
supervise him enough while he plays.  At the same time, we have to get
ourselves showered, dressed, teeth cleaned, and sometimes shaved, hair
washed and dried.  Every evening, we need to pick up Luke, take him
home, prepare his dinner, give him dinner, give him his bath and brush
his teeth, read him stories, and put him to bed.

My work is flexible enough that I can arrive late or leave early in
order to do drop off or pick up, but I still need to put in the hours.
So if I need to leave at 4.15pm to get to nursery in time, I need to
be at work well before 9.  And if I arrive at 9.45pm having done drop
off, I stay in til 6pm.

We have struggled with a particularly gnarly hazard that if we don't
explicitly talk about things, we both end up assuming that Sonia will
get involved and pick up the slack.  There are at least two reasons
for this: one is around [[https://www.theguardian.com/lifeandstyle/2015/nov/13/oliver-burkeman-overfunction-underfunction-relationship][overfunctioning versus underfunctioning]] (and
there are definite gender issues here, too), and the other is the
practical fact that Sonia works from home, so if I'm doing drop off or
pick up, she's still around to help with breakfast or dinner.  This
isn't entirely one-way, either: I find it difficult to leave early in
the morning when there's still breakfast things to clear away, washing
up to do, 

We took each week as it came, made plans around who does pick up and
who does drop off, and chatted at the end of each week to see how
things had gone, what went well and what could be improved.

Some of the things we have learned after painful experience are:

   - it's very important to keep talking about things, especially
     while the routine is still forming
   - we need to have clear expectations about who is lead parent, and
     when the other parent is around but has work responsibilities and
     therefore can't help
   - having dinner options for Luke that can be prepared in a short
     time with minimal effort takes up-front planning and effort

This week, Sonia had a business trip to Scotland from Tuesday to
Thursday, so I had to do Tuesday pick up, Wednesday looking after Luke
all day, and Thursday drop off, all alone.  That really helped me
build my confidence that I can do the morning and evening routines on
my own, and helped me to see all the things Sonia had previously been
getting involved in that she maybe didn't need to.

** Walking

Luke is now walking!  He had been cruising (walking while holding on
to the furniture) for some months, then a couple of weeks ago he took
his first freestanding steps.  There were a few days of taking 3-4
steps and collapsing on his bum, but pretty soon he was taking longer
walks, and even squatting down to pick things up and standing back up
again.  He's now very confident walking everywhere, and we rarely see
him crawl at all any more.

I had worried that walking would make him even harder to supervise
when playing, but it's actually been more mixed.  When he started
crawling, we needed to babyproof much more, such as moving things out
of his reach.  We needed to do a bit more of that for walking, since
he can reach a bit higher now.

But one thing I didn't anticipate is how taking Luke to the park is
much less effort and more reward now that Luke is walking.  When he
was crawling, he would be much closer to the ground, and he would find
things there that he'd put in his mouth.  I have horrible memories of
trying to fish a cigarette butt out of his mouth that he'd found and
immediately put in there.  Now he's walking, he does much less of
that, and he can engage with the actual play equipment much more.  So
where previously I'd have to keep a very close eye, and perhaps take
him from one piece of play equipment to another, now I just let him
walk where he fancies and slowly stroll round behind him.

Another thing about walking is that he can now get from one place to
another while carrying an object.  He showed us this by stealing
another boy's ball when we were at the park and walking around
carrying it.  So we've got him his own ball, and now he loves picking
it up, throwing it, and chasing after it.  He has such a big grin on
his face when he has his ball, and it's clearly such great exercise
for him.  He's not just practising his walking, he's also practising
squatting, balancing while his hands are full, and kicking a ball.

The loveliest part of this is that he now he can rake around his
collection of books, choose one, and bring it to me to read to him.
Walking means that he is in control of which books we read, instead of
me picking for him.  I hadn't appreciated how walking would change the
dynamic of so many of our interactions!
