---
layout: post
title: Dad Weeknotes, volume 5
tags:
  - dadding
  - weeknotes
---

I have successfully finished my fifth week of dadding.  You may also
want to see volumes [[/2018/01/13/dad-weeknotes-1.html][1]], [[/2018/01/20/dad-weeknotes-2.html][2]], [[/2018/01/27/dad-weeknotes-3.html][3]] and [[/2018/02/04/dad-weeknotes-4.html][4]].

** Shoes

We bought Luke's first pair of shoes this week.  He hasn't needed
shoes before because he hasn't started walking yet.  He has been
[[https://www.youtube.com/watch?v=gZl-G40BGX4][cruising]] for a while now, but this has been indoors.  However, now he
has started at nursery, and they encourage outside play, he really
needs to be wearing shoes.

We already had some hand-me-downs that were roughly the right size,
which is what he's been wearing at nursery for the past few weeks, but
Luke didn't look comfortable in them, and he either pulled them off or
they fell off by themselves.

We went to Clark's and got his feet properly measured and bought a
proper pair of crawling/cruising shoes.  The difference was
immediately apparent: he looked comfortable, didn't try to take them
off, and was happily cruising around the shoe shop bench straight
away.  I think they'll make a big difference!  It's just a shame they
won't last long as he'll grow out of them so soon.

** Nursery

Luke has been progressing at nursery.  Again, I took him in Monday to
Wednesday to help him further acclimatize.  On Thursday he stayed til
3pm again, and Friday til 4 – the latest he's ever stayed.

He's been coming home covered in paint, pen, sand, all sorts.  I think
this shows he's having a great time!

** Health

This week, Luke had his [[https://www.nhs.uk/conditions/pregnancy-and-baby/baby-reviews/#when-your-baby-will-have-their-reviews][12 month health visitor check]].  It was
actually one of the more fun appointments we've had.  There were no
needles or physical manipulation of joints.  Luke had his weight,
length and head circumference measured, then he was given some toys to
play with, and the health visitor observed his reactions.  The health
visitor was clearly someone who loved her job: she was really good
with Luke at keeping him interested in the examination and making
everything into a bit of a game for him.

Luke's been having some funny days where he has a much lower appetite
than usual.  He just eats much smaller portions than we're used to.
But otherwise he's absolutely fine: just as happy and interested in
things as usual, if maybe a little subdued.  He's also been a bit
snotty, so we're hoping it's just a cold or something.

** Milk

We've still not found a great breastmilk substitute for Luke during
the day.  He didn't take well to the wysoy formula (see [[/2018/01/20/dad-weeknotes-2.html][volume 2]]) and
we suspect he may also have a soya allergy.  After taking advice from
the dietician, we've been trying oat milk, but after some initial
hopeful attempts, he's shown less and less interest over time.

This week, I tried to introduce coconut-based milk instead.  Again,
there was some early success – he managed around 60ml the first time –
but I was struggling to get him to still be interested once the
novelty had worn off.  I have tried taking a drink from his cup
myself, to show him how it's done and to set an example, with varying
success.

Sonia made a breakthrough, though, when she offered him some milk in
an open cup, rather than the sippy cup we had been trying.  He seems
to like drinking from an open cup, though he needs much closer
supervision to avoid spilling it all!  We shall see if his interest
stays high or if it again wanes as the novelty wears off.

** Social stuff

Once again, I got out to my Thursday night orchestra.  With my new
free time during nursery on Thursday and Friday, I managed to meet
some friends for coffee and lunch.

Sonia (aka mum) even managed to have three nights out: Monday,
Tuesday, and Thursday.  I'm really pleased we're able to have some
sort of "normal" social life.
