---
layout: post
title: Dad Weeknotes, volume 4
tags:
  - dadding
  - weeknotes
---

Slightly late, here are my notes from my fourth week of dadding.  You
may also want to see volumes [[/2018/01/13/dad-weeknotes-1.html][1]], [[/2018/01/20/dad-weeknotes-2.html][2]] and [[/2018/01/27/dad-weeknotes-3.html][3]].

** New recipes

I tried two new big-batch recipes, both of which Luke loved: [[http://www.foodandwine.com/recipes/lamb-stew-root-vegetables][lamb stew
with root vegetables]], and [[https://www.jamieoliver.com/recipes/pasta-recipes/kerryann-s-tuna-pasta-bake/][tuna pasta bake]].  The pasta bake did the
whole family for three separate meals, and the lamb stew made 6
2-portion boxes for the fridge and freezer.  I think both will become
regular additions to the repertoire!

** Nursery

I spent a lot of time at nursery this week!  I took him in for an hour
on Monday and Wednesday mornings, to get him more familiar with the
staff, the routine, and the environment.  Then Thursday was the big
test: having had a bad time last Friday when we left him alone, we
wanted to do everything to help him settle without his mum or dad
there.  We brought his pram to sleep in as something more familiar
than the nursery mattresses, and we also brought his plushy duck
comforter.  And fortuitously, one of his NCT buddies started nursery
that day too.  The effort spent familiarizing him with the place
seemed to pay off, and he managed 9.30am til 12 noon without too much
drama.  They both seem to have helped him settle in too.

However, he was a very hungry boy on Thursday afternoon – eating a
bigger afternoon snack than usual, and also eating a big dinner.  At
nursery he had had a "large"-sized lunch; I wonder if that's still not
as big as what he's used to at home?

I also learned my lesson from last week, and arranged to do something
to keep myself busy rather than having nothing to do but worry about
Luke.  I went to meet an old friend for coffee and a catch up.  She
politely tolerated me showing her about 80 photos of Luke, for which I
am most grateful.  It was also comforting to know that our NCT friends
were there for their own baby's first day.

On Friday, we tried 9am til 2pm.  I dropped him off, and again went
somewhere nearby and kept busy.  He again did well, but he was
incredibly tired when we picked him up.  He had had 2 naps at nursery,
but he had a third nap that afternoon – something unheard of for him!
Having him so tired made the rest of the afternoon much harder work,
but I still think it's a good sign that he's using up all this energy
at nursery.

Next week, I'm planning to take Luke in on the off days again (Monday
to Wednesday) and hopefully he'll stay a little bit longer on Thursday
and Friday once more.

** Other stuff

I'm struggling to find things to write about.  The week has flown by,
and although I tried to keep notes as it went, I just don't feel like
there's much of note.  There was plenty more routine housework:
washing, washing up, that kind of thing.  I took Luke to the Tuesday
health visitor baby clinic to get some advice on some nappy rash.
They also weighed him (he's 11.10 kg, which is around the 90th
centile).  I found some time to do some filing, and noticed that our
fixed-price gas & electric deal has expired, so it's time to do some
shopping around for that again.  On Wednesday Sonia looked after Luke
for the afternoon, and so of course I had a raging migraine all
afternoon.  We managed to do some sociable stuff.  Sonia and I managed
to go to our respective orchestra rehearsals on Tuesday and Thursday,
we hosted Sonia's book club on Monday, I managed to buy some climbing
shoes at get back on the wall for the first time since 2016.

I'm keeping busy, I suppose?
