---
layout: post
title: "Dadding, season 2: the first few days"
tags:
  - dadding
  - weeknotes
---

It's time for season 2 of my dad notes.  I recently had my second
child and I'm on paternity leave.  So I thought I'd jot down some
notes of my experiences again.

This isn't a full week, it's just a few days, but they were an
incredibly intense few days.

** The birth

I got a call at work from my wife, Sonia, at lunchtime.  She was
feeling contractions, but she had felt them before and they had gone
away again.  It's surprisingly difficult to know if you are genuinely
in labour.  But my work is very flexible, so I was able to just go
home and work from home.

I went to pick up my eldest, Luke, from nursery at 5pm.  We decided to
leave him with a neighbour, just in case.  When I got home from the
neighbour's, I'd been away maybe 50 minutes and Sonia had clearly
progressed.  She showed me the timings of contractions that she'd
measured on her phone, and I called the midwife immediately.

We had planned a home birth, so various people came to our house.  We
had a lovely team – two midwives, a student midwife, a [[https://en.wikipedia.org/wiki/Doula][doula]], and my
mother-in-law.  My mother-in-law was an excellent host: she cooked a
nice dinner for everyone downstairs while Sonia and I were in our
cocoon upstairs labouring and preparing for birth.  We could hear the
happy noises of a dinner party while we just sat together and hugged
and focussed on our love for each other.  Sonia was in a really good
mental state.  She used hypnobirthing and mindfulness techniques to
get into a calm mental state; it was her second time going through the
experience of childbirth; and we didn't have to worry about getting to
the hospital (a significant source of stress from first time round).

As the evening progressed, the contractions got more and more intense.
Her meditative composure had been gradually but entirely replaced by
an animal instinct.  Soon it was time to push the baby out.  Even I
got physically involved, supporting her body weight to help her get
one leg up to give the baby more room.  Our beautiful baby arrived at
9.06pm and was passed to mum for his first cuddle.  It was an
incredibly special experience to be with Sonia through this.

However, even though this was the climactic moment after 9 months, it
was by no means the end.  Once the baby came out, he was quite blue in
the face and took some stimulation to get him to cry.  He had a
low-ish 1-minute [[https://en.wikipedia.org/wiki/Apgar_score][Apgar score]] and, even though this had improved by 5
minutes, we were concerned.  Sonia still had the third stage of labour
to go through (ie delivering the placenta).

We decided to go to hospital to get the baby checked out.  We had
pre-packed hospital bags for Sonia and baby, and I threw some things
together for myself, and we got in the ambulance and headed over.  The
paediatrician wasn't overly concerned, but recommended we stay for a
few hours of observations, which effectively meant an overnight stay.

** Day 2

So we stayed the night in hospital.  I think Sonia and I got an hour
of sleep in total between us that night.  Sonia had the bed – I had to
make do with a blow-up camping mattress.  But baby had been fine
overnight and so we were free to go home.

The baby (we still hadn't decided on a name) was very hungry that day.
It seems a bizarre design, but mother's breastmilk doesn't "come in"
until baby has been trying to feed for some time.  There is small
amounts of [[https://en.wikipedia.org/wiki/Colostrum][colostrum]] before that point but basically there isn't
enough food for the baby.  Newborns generally lose quite a bit of
their birthweight during this time.

In our case, our baby was clearly desperately hungry and kept feeding
for an incredibly long time.  This caused Sonia significant pain and
discomfort but it did help her milk to come in in the following days.

We still had to come up with a name.  We decided we wanted a name
before Luke, our eldest, met him, which meant before Luke got back
from nursery.  In the end, we chose the name Robin.

We gave Luke a present "from Robin" to make the first impression
easier.  So far, Luke seems proud to tell other people that he's a big
brother but mostly continues as he was ignoring Robin's existence.  I
call that success.

** The birthday

Through poor planning on our part, day 3 of our baby's life was also
his big brother's third birthday.  Thankfully, it was the day of the
week he spends with his nanny, who took him for a special trip to the
Science Museum.  He had a great time there.

Meanwhile, we had to do our newborn checks for Robin.  The plan was
for a community midwife to do them at our home, but the midwife was
ill, so we had to go into hospital (again) to get them done.

It's hard to communicate just how difficult a trip to hospital and
back was for us in those early days.  We hadn't slept, Sonia had just
given birth 36 hours beforehand and definitely wasn't "recovered" –
she couldn't walk further than a few tens of metres without
significant pain and discomfort – the baby was still hungry because
her milk hadn't come in, and in this semi-conscious battle-worn state
we had to get our baby into a taxi and out the other side, then find
the right ward in hospital to have his checks done.

We went home and tried to get some proper sleep.  But Robin woke us
every 2–3 hours, as newborns do.

My father-in-law also arrived on this day, giving us some extra
practical support so we didn't have to worry about cooking/washing
up/cleaning/laundry.

** In summary

Birth is an incredible experience, but it is also exhausting.  Then,
having gone through it, there's no respite: the hours, days and week
after birth are also exhausting.  We couldn't have got through it
without wonderful support from lots of lovely people.
