---
layout: post
title: "Dadding, season 2 minisode: what dads can do at night"
tags:
  - dadding
  - weeknotes
---

This is a short entry to capture something I wanted to write down now
rather than waiting for the next full update.

Newborn babies need to feed a lot – [[https://www.nhs.uk/conditions/pregnancy-and-baby/breastfeeding-first-days/][at least 8 to 12 times, or more,
every 24 hours during the first few weeks]].  We are breastfeeding,
which means that all of this feeding has to be done by mum.  It's too
early to start pumping milk and introducing a bottle.  So what can I,
as a dad, do?

** Nappy changes

A newborn baby has three basic needs: feeding, nappy changes, and
sleep.  As a dad, I've taken on a lot of the nappy changes: in
particular, all nappy changes at night.  During the night, mum feeds,
and I change the nappy afterwards.  This means that mum is awake
longer than me (nappy changes are quicker than feeds), but mum doesn't
have to actually get out of bed.  (As an aside, I'm not sure how
possible this would be if I was back at work, as I would already be if
I had just taken Paternity Leave and not Shared Parental Leave as
well.)

This has required some active communication between Sonia and me.
Sometimes she has to wake me up to get me to change a nappy, which
can't be a nice thing to have to do to someone.  I have to reinforce
that this is okay and expected: both by affirming during the day
("yes, please wake me up for nappy changes, this is fine") and by
being mindful of my body language at night.  Waking up in a standard
grumpy way does not help Sonia feel good about calling on my help.  So
I've been consciously trying to smile at her when she wakes me up.
This takes some effort but it really helps us feel we're doing nights
together as a team!

** Comforting

Although a baby only has 3 basic needs, that doesn't mean every time
the baby cries you need to do one of those things.  Sometimes, the
baby is crying, and we try a feed, change nappy, and put him back in
his Moses basket, and he is still crying.  His basic needs are clearly
met but he's still upset.

It's tempting to just keep feeding – breastfeeding is a great comfort
to babies, even if mum's milk supply is completely depleted.  There
have been a couple of episodes where Robin has spend multiple hours on
the breast, when he could have got the same amount of milk in separate
feeds spaced 2-3 hours apart.

But another option is just to try comforting him.  It's not easy, and
it doesn't have a high success rate, but when you get a crying baby to
sleep just through some cooing and rocking, it feels like a huge
accomplishment.  One thing I do that has a decent track record of
getting him comforted is to pick him up and walk up and down the
stairs with him.  This is also great exercise for me.  Somehow the
stairs are key: I don't get the same results walking around on the
flat, somehow.

Another thing I've had moderate success with is using my [[https://en.wiktionary.org/wiki/pinkie][pinkie]] as a
dummy for him to suck on.  If we're confident that he's already
well-fed (because he just had a feed 5 minutes ago and because Sonia
has no milk left), sometimes I give him my pinkie and he gives it a
good suck.  This can be enough for him to slowly get off to sleep,
with my finger still in his mouth, which I then have to carefully
extract without waking him.  Other times, he seems to recognise that
this isn't the real deal and tries to push me away with his little
hands.

There has been a couple of times when he was being particularly
demanding for food, and Sonia was absolutely exhausted but couldn't
see any way out.  I find it important not to give up and to assume
that this is her job to deal with, and to at least try to comfort
Robin for a bit.  The worst case scenario is that I try comforting for
10 minutes and he's still crying, but at least Sonia's had a 10 minute
break; the best case is that I get him off to sleep completely.
