---
layout: post
title: "Dadding, s2e3: It's been hard work"
tags:
  - dadding
  - weeknotes
---

It's been nearly a month since the last update, which was not my
intention.  It's been hard work, and I haven't really found time to
write anything, because we've been so busy just getting through each
day.  Bringing up children in a lockdown is not easy and we've been
finding it tough.

** Some perspective

I want to prefix all of this with: we are by no means the only people
suffering in this pandemic, and we are in many ways very fortunate.
Although this post will go into some detail about our difficulties, I
don't for a minute think we are under great hardship in absolute
terms.

I'm on shared parental leave, so I have a stable income and I don't
currently have any work obligations.  My wife isn't working.  So we
have two parents to look after two children.  We have a garden, so we
have access to outside space whenever we want.

We have good neighbours who we can call on for things – for example,
when we were self-isolating we got a neighbour to drop off some
paracetamol for us.

Our baby, Robin, was born before the lockdown was announced, so we
could have the birth at home and we got all the antenatal checks and
things done in time ([[/2020/03/23/dadding-s2e2.html][see previous post]]).

** Juggling two kids with no support

The last few weeks have been really difficult.  We've mostly been
getting through each day as it comes, then going to bed early because
we're both so exhausted, only for it all to start again the next day.

We are suddenly having to look after two children full time without
any of the usual support.  For our 3-year-old, Luke, we previously had
nursery 3 days a week, and a nanny one day; we now have him full time.
He's at an age where he's very inquisitive and curious, learning a lot
about the world, and starting to assert his own identity as well.
This makes for some challenging behaviour at times – when he doesn't
get his way, he's taken to throwing things at us.  Overall it's a
fairly high-maintenance life stage: he can't really be left to play on
his own for that much time each day.  He really craves interaction
with us and needs practical help from us with all sorts of things:
playing with his train set, having a bath, getting dressed or
undressed, sitting on the potty, etc.  That said, we can plug him into
CBeebies for half an hour or so at a time when we really need some
time to ourselves (say, to go to the toilet or have a shower!)

Luke needs a lot of exercise.  We take him out each day, but of course
all the playgrounds are sensibly closed, so we've had to think about
where we go when we go out.  Where is responsible (limiting risk of
spreading coronavirus), will keep Luke engaged, doesn't require public
transport?  The parks are still open, so we do take Luke to parks
occasionally, but if he sees another child he knows from nursery or
from our neighbourhood he just wants to run over and play with them.
He's just getting to the age where he's starting to interact
meaningfully with other children, and it's heartbreaking to keep
telling him "don't get too close!" "no touching!" "we can't share other
people's toys!"

One thing we've been doing is taking him out on his balance bike to
see the railway line at the top of our road.  There's a gate in the
railway fence, set back from the pavement, where we can stand and
watch trains, which he loves.  However, because it's still next to the
road, you can't fully switch off as parent.

We've also found a park which is in the direct opposite direction to
nursery, where we rarely bump into children Luke knows, and where the
density of people is generally low enough that Luke can run around
without getting within 6 feet of anyone.

For our baby, Robin, the first few weeks of a baby's life you kind of
stay at home most of the time anyway, but we're now getting to the
point where, outside a lockdown, we'd be starting to take him to local
groups.  Postnatal mum-and-baby yoga was something Sonia really
enjoyed from Luke's baby months (and I even found a dad-and-baby yoga
group).  The Salvation Army hosted a twice-weekly stay-and-play even
where we could have taken both Luke and Robin, Luke can run around in
a safe environment without requiring too much supervision, and you can
meet other parents and chat and support each other.  It's been hard to
let go of what might have been – those support groups would have been
invaluable but they're just not available to us.

On a practical note, we've told our cleaner not to come any more (and
we offered to keep paying her regardless).  Luke generates a lot of
mess and we've had to take on more of the cleaning ourselves.

Our days are packed.  The only time which kind of belongs to ourselves
is when the kids are asleep.  Luke has an afternoon nap, which means
we have an hour or two then (although much of this time we spend
clearing up after lunch, tidying his toys away, etc).  And Luke's
bedtime has been creeping later and later, so that he might not be
settled in bed until 9pm.  We ourselves are so tired that we're
usually in bed before 10pm.  This means that, on a good day, we might
have an hour to ourselves in the afternoon and another hour in the
evening, when we're too tired to do anything.

** Too much perspective?

My wife and I do remind each other how lucky we are a lot.  I think it
is useful to maintain perspective, but I wonder if it's also been
having a negative effect: it's easy to think "if other people are
coping under worse conditions, why are we finding it hard?"  This
thought is pernicious.  It makes our struggles feel like a personal
failing, which makes us feel even worse about ourselves.

I've been thinking about a section in Robert Webb's autobiographical
/[[https://canongate.co.uk/books/2395-how-not-to-be-a-boy/][How Not To Be a Boy]]/ (which is an excellent book and I highly
recommend).  While he was at university, Webb was suffering mental
health issues, and he went to the university counselling service.  He
made various comments about how his problems were nothing, really, and
he probably was wasting the counsellor's time and other people
probably had much bigger problems.

#+BEGIN_QUOTE
Robert, I get this from students all the time, especially the male
students.  Yes /of course/ there is always someone worse off than you.
But imagine you're in a doctor's surgery with a broken arm. The person
next to you has two broken arms, the person next to him has two broken
arms and a broken leg.  This is all very well, but the point is that
you have a broken arm and it /hurts/.
#+END_QUOTE

Sonia also found [[http://www.suzannezeedyk.com/fed-up-of-being-cooped-up-in-lockdown-with-the-kids/][this blog post by Dr Suzanne Zeedyk]] which we both
found helpful.  It describes the importance of not trying to be
perfect parents; it's ok to just be good enough parents.
